document.addEventListener('DOMContentLoaded', function () {
    const languageDropdown = document.getElementById('languageDropdown');
    const languageList = document.getElementById('languageList');
    const languageIcon = document.getElementById('languageIcon');
    const currentLangElement = document.querySelector('[data-translate="currentLang"]');


    languageDropdown.addEventListener('click', function (event) {
        event.preventDefault();
        languageList.style.display = languageList.style.display === 'block' ? 'none' : 'block';
    });


    languageList.querySelectorAll('a').forEach(function (langLink) {
        langLink.addEventListener('click', function (event) {
            event.preventDefault();
            const selectedLang = this.getAttribute('data-lang');
            changeLanguage(selectedLang);
            languageList.style.display = 'none';
        });
    });


    function changeLanguage(lang) {

        if (lang === 'RU') {
            languageIcon.src = 'src/img/icons/languagemask.svg';
            currentLangElement.textContent = 'RU';
        } else if (lang === 'ENG') {
            languageIcon.src = 'src/img/icons/en-lang.svg';
            currentLangElement.textContent = 'ENG';
        }
        const nameInput = document.querySelector('.application__name');
        if (nameInput) {
            nameInput.placeholder = translations[lang].placeholderName;
        }


        document.querySelectorAll('[data-translate]').forEach(function (element) {
            const key = element.getAttribute('data-translate');
            element.textContent = translations[lang][key];
        });
    }

    const translations = {
        RU: {
            tariffs: 'Тарифы',
            bonus: 'Бонус',
            referal: 'Реферальная',
            contacts: 'Контакты',
            currentLang: 'RU',
            login: 'Войти',
            check: 'Открыть счет',
            top1: 'Станьте миллионером с Leader Classic',
            top2: 'Откройте счет, инвестируйте в фонды Leader Classic и получите шанс выиграть один из 100 000 000 ₽',
            timer1: 'д',
            timer2: 'ч',
            timer3: 'м',
            timer4: 'с',
            top: 'ТОП-5 акций',
            med: 'с доходностью до 10-30% ',
            bot: 'уже в 2022 году',
            item1: 'Открытие брокерского счета за 5 минут без визита в офис',
            item2: 'Доступ к ценным бумагам с любого устройства',
            item3: 'Поддержка в чате 24/7',
            shortbut: 'Скачать ТОП-5 акций',
            shortbut1: 'Открыть счёт',
            tr1: 'Сейчас инвестируют 100 000+ пользователей',
            tr2: 'Ваши деньги',
            tr3: 'способны на большее',
            tr4: 'Сколько бы вы заработали, инвестируй',
            tr5: 'год назад?',
            tr6: 'И еще более 10 000 других ценных бумаг доступно в каталоге',
            tr7: 'Получить каталог',
            tr8: 'Большой выбор инструментов',
            tr9: 'Инвестиции доступные каждому',
            tr10: 'Простой сервис с подсказками и поддержкой 24/7 на каждом этапе',
            tr11: 'Шаг 1',
            tr12: 'Заполнить регистрационную анкету',
            tr13: 'Нужно указать основные данные о себе: имя, номер телефона, e-mail и пароль для входа.',
            tr14: 'Шаг 2',
            tr15: 'Внести деньги',
            tr16: 'на счет',
            tr17: 'Вы можете использовать несколько платежных систем для пополнения депозита, включая систему MidexPay и кошелек Bitcoin.',
            tr18: 'Шаг 3',
            tr19: 'Приступить к онлайн-трейдингу',
            tr20: 'Сразу после пополнения депозита торговля через веб-терминал или мобильную платформу будет доступна.',
            tr21: 'Сейчас инвестируют 100 000+ пользователей',
            tr22: 'БОНУС',
            tr23: 'Каждый достоин',
            tr24: 'второго шанса',
            tr25: 'Купите свои первые акции без риска, мы вернем',
            tr26: 'вам 100$ на счет в случае проигрыша',
            tr27: 'Получить бонус',
            tr28: 'Открыть демо-счёт',
            tr29: '100 000+ клиентов уже инвестируют с нами',
            tr30: 'Представительство компании в Европе',
            tr31: 'В разных странах мира компания открывает собсвенные представительства.',
            tr32: 'Подробнее',
            tr33: 'Мгновенный ввод и вывод средств',
            tr34: '0% комиссия с депозита',
            tr35: 'Кредитное плечо до 1:1000',
            tr36: 'Время выполнения заказа - 30 мс',
            tr37: 'Средний показатель по отрасли - 500 мс',
            tr38: '250 торговых инструментов',
            tr39: 'Валютные пары, акции, металлы, индексы, облигации',
            tr40: 'Счета в евро, рублях, долларах США',
            tr41: 'Пополните свой счет и сэкономьте на сборах за конвертацию',
            tr42: '15% бонус на первый депозит',
            tr43: 'Может использоваться в торговле и во время просадки',
            tr44: 'Инновационная торговая платформа МТ5',
            tr45: 'Доступно на IOS и Android',
            tr46: 'Доходность',
            tr47: 'до',
            tr48: 'Низкий риск',
            tr49: 'Управляю деньгами сам',
            tr50: 'Доверяю управление',
            tr51: 'Подберите индивидуальный инвестиционный портфель',
            tr52: 'Покупайте российские и иностранные акции, облигации, валюту и другие продукты в простом и удобном мобильном приложении для iOS и Android',
            tr53: 'Получить бонус',
            tr54: 'Активных инвесторов',
            tr55: 'Торговых инструментов',
            tr56: 'Финансовый результат',
            tr57: 'одного из инвесторов',
            tr58: 'Инвестируйте с телефона',
            tr59: 'Покупайте российские и иностранные акции, облигации, валюту и другие продукты в простом и удобном мобильном приложении для iOS и Android.',
            tr60: 'Скачать для IOS',
            tr61: 'Скачать для Android',
            tr62: 'Мне только спросить',
            tr63: 'Собрали в подсказках ответы на популярные вопросы об инвестициях и сервисе',
            tr64: 'Получить консультацию',
            tr65: 'Есть ли плата за обслуживание?',
            tr66: 'Как вывести деньги со счёта?',
            tr67: 'Какие налоги?',
            tr68: 'Где хранятся деньги?',
            tr69: 'Как открыть счёт?',
            tr70: 'Как пополнить счёт?',
            tr71: 'Что купить?',
            tr72: 'Оставьте заявку на открытие счёта',
            tr73: 'Заполните заявку',
            tr74: 'онлайн',
            tr75: 'Необходимо: имя, номер телефона, e-mail и пароль для входа.',
            tr76: 'Откроем счет',
            tr77: 'за 5 минут',
            tr78: 'Вы можете использовать несколько платежных систем для пополнения депозита, включая систему MidexPay и кошелек Bitcoin.',
            tr79: 'Пополните счёт',
            tr80: 'и начните инвестировать',
            tr81: 'Сразу после пополнения депозита будет доступна торговля через веб-терминал или мобильную платформу.',
            tr82: 'Оставить заявку',
            placeholderName: 'Ваше имя:',
            tr84: 'Политика передачи данных',
            tr85: 'Звонок по России бесплатный',
            tr86: 'Оставить заявку',
            tr87: '',
        },
        ENG: {
            tariffs: 'Tariffs',
            bonus: 'Bonus',
            referal: 'Referral',
            contacts: 'Contacts',
            currentLang: 'ENG',
            login: 'Log in',
            check: 'Open an account',
            top1: 'Become a millionaire with Leader Classic',
            top2: 'Open an account, invest in Leader Classic funds and get a chance to win one of ₽100,000,000',
            timer1: 'd',
            timer2: 'h',
            timer3: 'm',
            timer4: 's',
            top: 'TOP-5 stockswith',
            med: 'yield up to 10-30%',
            bot: 'already in 2022',
            item1: 'Open a brokerage account in 5 minutes without visiting the office',
            item2: 'Access to securities from any device',
            item3: 'Chat support 24/7',
            shortbut: 'Download TOP-5 stocks',
            shortbut1: 'Open an account',
            tr1: '100,000+ users are currently investing',
            tr2: 'Your money',
            tr3: 'can do more',
            tr4: 'How much would you have earned if you invested',
            tr5: 'a year ago?',
            tr6: 'And more than 10,000 other securities are available in the catalog',
            tr7: 'Get catalog',
            tr8: 'Large selection of tools',
            tr9: 'Investments available to everyone',
            tr10: 'A simple service with tips and 24/7 support at every stage',
            tr11: 'Step 1',
            tr12: 'Fill out the registration form',
            tr13: 'You need to provide basic information about yourself: name, phone number, e-mail and password to log in.',
            tr14: 'Step 2',
            tr15: 'Deposit money',
            tr16: 'to the account',
            tr17: 'You can use several payment systems to replenish your deposit, including the MidexPay system and Bitcoin wallet.',
            tr18: 'Step 3',
            tr19: 'Start online trading',
            tr20: 'Immediately after replenishing the deposit, trading via the web terminal or mobile platform will be available.',
            tr21: '100,000+ users are currently investing',
            tr22: 'BONUS',
            tr23: 'Everyone is worthy',
            tr24: 'second chance',
            tr25: 'Buy your first shares risk free, we will refund',
            tr26: 'you get $100 to your account in case of loss',
            tr27: 'Get a bonus',
            tr28: 'Open a demo account',
            tr29: '100,000+ clients already invest with us',
            tr30: 'Representative office of the company in Europe',
            tr31: 'The company opens its own representative offices in different countries around the world.',
            tr32: 'Details',
            tr33: 'Instant deposits and withdrawals',
            tr34: '0% commission on deposit',
            tr35: 'Leverage up to 1:1000',
            tr36: 'Order execution time - 30 ms',
            tr37: 'Industry average: 500 ms',
            tr38: '250 trading instruments',
            tr39: 'Currency pairs, stocks, metals, indices, bonds',
            tr40: 'Accounts in euros, rubles, US dollars',
            tr41: 'Top up your account and save on conversion fees',
            tr42: '15% bonus on your first deposit',
            tr43: 'Can be used in trading and during drawdowns',
            tr44: 'Innovative trading platform MT5',
            tr45: 'Available on IOS and Android',
            tr46: 'Profitability',
            tr47: 'up to',
            tr48: 'Low risk',
            tr49: 'I manage my money myself',
            tr50: 'I trust the management',
            tr51: 'Choose a customized investment portfolio',
            tr52: 'Buy Russian and foreign stocks, bonds, currencies and other products in a simple and convenient mobile application for iOS and Android',
            tr53: 'Get bonus',
            tr54: 'Active investors',
            tr55: 'Trading instruments',
            tr56: 'Financial result',
            tr57: 'of one of the investors',
            tr58: 'Invest from your phone',
            tr59: 'Buy Russian and foreign stocks, bonds, currencies and other products in a simple and convenient mobile application for iOS and Android.',
            tr60: 'Download for iOS',
            tr61: 'Download for Android',
            tr62: 'I just have to ask',
            tr63: 'We have collected answers to popular questions about investments and services in tips',
            tr64: 'Get a consultation',
            tr65: 'Is there a service charge?',
            tr66: 'How to withdraw money from an account?',
            tr67: 'What taxes?',
            tr68: 'Where is the money kept?',
            tr69: 'How to open an account?',
            tr70: 'How to top up your account?',
            tr71: 'What to buy?',
            tr72: 'Leave a request to open an account',
            tr73: 'Fill out the application',
            tr74: 'Online',
            tr75: 'Required: name, phone number, e-mail and password to log in.',
            tr76: 'Let`s open an account',
            tr77: 'in 5 minutes',
            tr78: 'You can use several payment systems to replenish your deposit, including the MidexPay system and Bitcoin wallet.',
            tr79: 'Top up your account',
            tr80: 'and start investing',
            tr81: 'Immediately after replenishing the deposit, trading will be available via the web terminal or mobile platform.',
            tr82: 'Leave a request',
            placeholderName: 'Your name:',
            tr84: 'Data Transfer Policy',
            tr85: 'Calls within Russia are free',
            tr86: 'Leave a request',
            tr87: '',
        }
    };
});

